### ISSUE TITLE
Card layout problems

### ISSUE THREAD

**Issue by kdima71** [WisdmLabs/moodle-format_remuiformat#62] opened 2022-08-21 10:01 UTC
Hi Edwiser Team!

I'm using Moodle 4.02 and the Moove theme, as well as Oracle DBMS

I set the Card layout template for the Course.

Course sections are displayed as Cards with Links to the contents of the section.

Selecting a Section displays its nested elements (pages, lectures, books, and so on) in the form of Cards, but without Links for navigating into the content.

Why are the links not showing up? What could be the problem?

Thanks in advance.

![изображение](https://user-images.githubusercontent.com/71516526/185785815-ec00c09c-a909-4007-a877-3bef80039125.png)

![изображение](https://user-images.githubusercontent.com/71516526/185785848-363e3a35-3785-4619-89e0-0ea13a74448f.png)

**Comment by xmontana** [comment] 2022-08-24 07:55
Hi!

We have the same problem with Moodle 4.0.3 (Build: 20220822), theme Boost and Mysql 5.3.7. 

The links code aren't rendered in the template:

<img width="885" alt="2022-08-24_09-52-59" src="https://user-images.githubusercontent.com/650776/186362565-ceb3b1c5-4471-4a29-95b7-a8481e5c29c2.png">

Older version of Moodle works correctly, but in some Moodle 4 core update broke the code.

Regards!

**Comment by KuMLuK** [comment] 2022-12-20 00:37
Hi!

This issue persists in Moodle 4.1+ (Build: 20221216) as well.

When will a RemUI version be released with this bug fixed?

**Comment by NathanJPlummer** [comment] 2022-12-22 21:03
For anyone else that might be having this issue:

With help from the Wisdom Labs team we found when moving the course from Moodle 3 to 4 (4.0.5) the setting for displaying the images on the course front page was automatically disabled. Manually re-enabling the setting fixed the issue.



![image](https://user-images.githubusercontent.com/16419908/209225096-d5e7ec62-e3bf-47d6-98b8-1894b7929fb6.png)

**Comment by xmontana** [comment] 2022-12-23 13:12
Thank you @NathanJPlummer for sharing the feedback, I try again (Moodle 4.0.5+ and Course Form) and changing with different values in "Section background image", but the problem is the text of the activities it is not rendered, so you cannot click to any activity.

**Comment by Beansworthy** [comment] 2023-01-30 22:16
@NathanJPlummer, Confirmed @xmontana's comment that changing the section background image setting does not fix this issue, it only changes the background image of section cards. Cards _within_ a section do not link to activities.

This is a working subcourse in List view:

![image](https://user-images.githubusercontent.com/87251686/215606559-b8c31716-5faf-4cb9-a405-70742ca43d59.png)

and this is Card View showing the same subcourse and a newly created assignment
![image](https://user-images.githubusercontent.com/87251686/215608048-82d0fb62-d03f-40ee-ab29-80f4aca4b78d.png)

Neither can be accessed.

**Comment by abhikushwah** [comment] 2023-05-09 09:02
This issue has been resolved in our latest release.

**Closed by abhikushwah** 2023-05-09 09:02 UTC
